PrepareData.com/PrepareData.Web/Models/Layout/LanguageSelectionViewModel.cs
using System.Collections.Generic;
using Abp.Localization;

namespace PrepareData.Web.Models.Layout
{
    public class LanguageSelectionViewModel
    {
        public LanguageInfo CurrentLanguage { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }
    }
}

PrepareData.com/PrepareData.Web/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace PrepareData.Web.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

PrepareData.com/PrepareData.Web/Models/Layout/UserMenuOrLoginLinkViewModel.cs
using PrepareData.Sessions.Dto;

namespace PrepareData.Web.Models.Layout
{
    public class UserMenuOrLoginLinkViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }
        public bool IsMultiTenancyEnabled { get; set; }

        public string GetShownLoginName()
        {
            var userName = "<span id=\"HeaderCurrentUserName\">" + LoginInformations.User.UserName + "</span>";

            if (!IsMultiTenancyEnabled)
            {
                return userName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + userName
                : LoginInformations.Tenant.TenancyName + "\\" + userName;
        }
    }
}

PrepareData.com/PrepareData.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration.Startup;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using PrepareData.Sessions;
using PrepareData.Web.Models.Layout;

namespace PrepareData.Web.Controllers
{
    public class LayoutController : PrepareDataControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ILocalizationManager _localizationManager;
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;

        public LayoutController(
            IUserNavigationManager userNavigationManager, 
            ILocalizationManager localizationManager,
            ISessionAppService sessionAppService, 
            IMultiTenancyConfig multiTenancyConfig)
        {
            _userNavigationManager = userNavigationManager;
            _localizationManager = localizationManager;
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var model = new TopMenuViewModel
                        {
                            MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                            ActiveMenuItemName = activeMenu
                        };

            return PartialView("_TopMenu", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
                        {
                            CurrentLanguage = _localizationManager.CurrentLanguage,
                            Languages = _localizationManager.GetAllLanguages()
                        };

            return PartialView("_LanguageSelection", model);
        }


        [ChildActionOnly]
        public PartialViewResult UserMenuOrLoginLink()
        {
            UserMenuOrLoginLinkViewModel model;

            if (AbpSession.UserId.HasValue)
            {
                model = new UserMenuOrLoginLinkViewModel
                {
                    LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations()),
                    IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
                };
            }
            else
            {
                model = new UserMenuOrLoginLinkViewModel
                {
                    IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled                    
                };
            }

            return PartialView("_UserMenuOrLoginLink", model);
        }
    }
}

PrepareData.com/PrepareData.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>医蟹网|千睿医蟹联盟</title>
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="~/favicon.ico">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="~/favicon.ico">
    <link rel="icon" href="~/favicon.ico" sizes="32x32">
    <!--  Android 5 Chrome Color-->
    <meta name="theme-color" content="#EE6E73">


    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body>
    @*<header>
            @Html.Partial("_TopBar")
        </header>*@
    
    @RenderBody()


    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- SignalR scripts -->
    @*<script src="~/signalr/hubs"></script>
    @Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")*@

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

PrepareData.com/PrepareData.Web/Views/Shared/_Layout_Home.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>医蟹网|千睿联盟</title>
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="~/favicon.ico">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="~/favicon.ico">
    <link rel="icon" href="~/favicon.ico" sizes="32x32">
    <!--  Android 5 Chrome Color-->
    <meta name="theme-color" content="#EE6E73">


    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body>
    <header>
        @Html.Partial("_TopBar")
    </header>
    <main>
        @RenderBody()
    </main>
    <!-- START FOOTER -->
    <footer class="page-footer" style="margin-top:0px;padding-top:0px;background-color:#ee6e73;">
        <div class="footer-copyright">
            <div class="container">
                <span>Copyright © 2016 <a class="grey-text text-lighten-4" href="http://www.mdevc.com" target="_blank">Xian qian rui network information co., LTD</a> All rights reserved.</span>
                <span class="right"> Design and Developed by <a class="grey-text text-lighten-4" href="#">Lu Henghui</a></span>
            </div>
        </div>
    </footer>
    <!-- END FOOTER -->

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- SignalR scripts -->
    @*<script src="~/signalr/hubs"></script>
    @Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")*@

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

PrepareData.com/PrepareData.Web/Views/Shared/_Layout_Index.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Prepare Data</title>
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="~/favicon.ico">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="~/favicon.ico">
    <link rel="icon" href="~/favicon.ico" sizes="32x32">
    <!--  Android 5 Chrome Color-->
    <meta name="theme-color" content="#EE6E73">


    @*@Styles.Render("~/Bundles/vendor/css")*@
    @Styles.Render("~/Bundles/Index/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>
   

</head>
<body>
    
    
    @RenderBody()


    @*@Scripts.Render("~/Bundles/vendor/js/bottom")*@
    @Scripts.Render("~/Bundles/Index/js")

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

PrepareData.com/PrepareData.Web/Views/Shared/_Layout_Web.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@using Abp.Web.Mvc.Extensions

<!DOCTYPE html>
<html>
<head>
    <meta name="renderer" content="webkit">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,Chrome=1">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>医蟹网|千睿医蟹联盟</title>
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="~/favicon.ico">
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="~/favicon.ico">
    <link rel="icon" href="~/favicon.ico" sizes="32x32">
    <!--  Android 5 Chrome Color-->
    <meta name="theme-color" content="#EE6E73">


    @Styles.Render("~/Bundles/vendor/css")
    <link href="~/Views/IndexDisplay/index.css" rel="stylesheet" />
    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body>
    <header>
        <div class="container">
            @*<div class="row">
                <div id="top_head" class="col s12 l12 ">
                    <div class="left"></div>
                    <div class="btns right-align">
                        <a class="waves-effect waves-teal btn-flat" href="/Account/Login" target="_blank">登录</a>|
                        <a class="waves-effect waves-teal btn-flat" href="#">注册</a>
                    </div>
                </div>
            </div>*@
            <nav class="z-depth-0 ">
                <div class="nav-wrapper">
                    <a href="/IndexDisplay/Index" class="brand-logo"><img class="responsive-img" src="~/Content/images/indexDisplay/qianruilogo.gif" /></a>
                    <ul id="nav-mobile" class="left hide-on-med-and-down"></ul>
                    @*<span class="brand-logo center" style="color:black;"><h4>医疗机构模板页</h4></span>*@
                    <form class="right hide-on-med-and-down">
                        <div class="input-field">
                            <input id="search" type="search" placeholder="请输入内容" required>
                            <label for="search" class="active"><i class="fa fa-search"></i></label>
                        </div>
                    </form>
                    <div class="btns right-align">
                        <a class="waves-effect waves-teal btn-flat" href="/Account/Login" target="_blank">登录</a>|
                        <a class="waves-effect waves-teal btn-flat" href="#">注册</a>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <div class="section">
        <div class="carousel-item">
            <img src="~/Content/images/indexDisplay/banner-2.gif">
        </div>
            @*<div class="carousel carousel-slider" data-indicators="true">
                <div class="carousel-item">
                    <img src="~/Content/images/indexDisplay/banner-4.jpg">
                </div>
                <div class="carousel-item">
                    <img src="~/Content/images/indexDisplay/banner-3.jpg">
                </div>
                <div class="carousel-item">
                    <img src="~/Content/images/indexDisplay/banner-2.gif">
                </div>
                <div class="carousel-item">
                    <img src="~/Content/images/indexDisplay/banner-1.jpg">
                </div>
            </div>*@
        </div>
    <div class="container">
        <div class="row">
            @*<div class="col s3 l2">
                    <div class="collection center">
                        <a href="#!" class="collection-item active">科室简介</a>
                        <a href="#!" class="collection-item">招标信息</a>
                        <a href="#!" class="collection-item">风采展示</a>
                        <a href="#!" class="collection-item">科室党建</a>
                        <a href="#!" class="collection-item">办事流程</a>
                        <a href="#!" class="collection-item">通知公告</a>
                        <a href="#!" class="collection-item">表格下载</a>
                        <a href="#!" class="collection-item">学习园地</a>
                    </div>
                </div>*@
            <div class="col s9 l9">
                @RenderBody()
            </div>
            <div class="col s6 l3">
                <div class="collection center">
                    <a href="#!" class="collection-item active">千睿云平台尊享服务区</a>
                    <a href="http://www.mdevc.com" class="collection-item" target="_blank">云管理平台</a>
                    <a href="http://www.mdevc.com" class="collection-item" target="_blank">千睿医蟹网</a>
                    <a href="http://www.mdevc.com" class="collection-item" target="_blank">采购招标系统</a>
                    <a href="http://www.mdevc.com" class="collection-item" target="_blank">采购订单系统</a>
                    <a href="http://www.mdevc.com" class="collection-item" target="_blank">资质目录系统</a>
                    <a href="http://www.mdevc.com" class="collection-item" target="_blank">物流链系统</a>
                    <a href="http://www.mdevc.com" class="collection-item" target="_blank">设备工程师平台</a>
                    <a href="http://www.mdevc.com" class="collection-item" target="_blank">设备成本效益分析</a>
                </div>
                <div class="collection operation center">
                    <a href="#!" class="collection-item active">千睿联盟站信息支持区</a>
                    <a href="#!" class="collection-item">找产品</a>
                    <a href="#!" class="collection-item">招代理</a>
                    <a href="#!" class="collection-item">市场询价</a>
                    <a href="#!" class="collection-item">征询参数</a>
                    <a href="#!" class="collection-item">招服务</a>
                    <a href="#!" class="collection-item">交流互动</a>
                    <a href="#!" class="collection-item">技术问答</a>
                </div>
            </div>
        </div>
    </div>
    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col l6 s12">
                    <h5 class="white-text">联系方式</h5>
                    <p class="grey-text text-lighten-4" style="height:15px;">电话：029-81885844</p>
                    <p class="grey-text text-lighten-4" style="height:15px;">邮箱：xaqryxjs@hotmail.cn</p>
                </div>
                <div class="col l4 s12">
                    <h5 class="white-text">友情链接</h5>
                    <ul>
                        <li><a href="http://www.mdevc.com" class="grey-text text-lighten-3" target="_blank">千睿医蟹网</a></li>
                        <li><a href="http://124.115.223.206:8089/gymis/" class="grey-text text-lighten-3" target="_blank">耗材供应商</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                &copy;2016 版权所有 西安千睿网络信息有限公司
                <a class="grey-text text-lighten-4 right" href="http://www.mdevc.com">最新、最全医疗器械信息，请上千睿医蟹网！</a>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/Bundles/vendor/js/bottom")

    <script>
        //Localizing momentjs
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name');
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>
    <script>
        function load_Menu(selected) {
            abp.ajax({
                url: abp.appPath + 'NavigationMenus/Tree',
                type: 'POST',
                success: function (result) {
                    var html = '<li ' + (selected ? 'class="active"' : '') + ' ><a class="waves-effect waves-light" href="' + abp.appPath + 'IndexDisplay/Index">网站首页</a></li>';
                    if (result && result.id == -1 && result.children.length > 0) {
                        $.each(result.children, function (index, item) {
                            if (item.children && item.children.length > 0) {
                                html += '<li ' + (item.id == selected ? 'class="active"' : '') + ' ><a class="dropdown-button waves-effect waves-light" href="#!" data-hover="true" data-belowOrigin="true" data-activates="dropdown' + item.id + '">' + item.text + '</a></li>';
                                var dropdown = '<ul id="dropdown' + item.id + '" class="dropdown-content">';
                                $.each(item.children, function (i, v) {
                                    dropdown += '<li><a class="waves-effect waves-light" href="' + abp.appPath + 'Articles/ListPage?mid=' + v.id + '">' + v.text + '</a></li><li class="divider"></li>';
                                });
                                dropdown += '</ul>';
                                $('body').append(dropdown);
                            } else {
                                html += '<li ' + (item.id == selected ? 'class="active"' : '') + ' ><a class="waves-effect waves-light" href="' + abp.appPath + 'Articles/ListPage?mid=' + item.id + '">' + item.text + '</a></li>';
                            }
                        });
                        $("#nav-mobile").append(html);
                        $(".dropdown-button").dropdown({ hover: true, alignment: 'bottom', belowOrigin: true });
                    }
                }
            });
        }
    </script>
    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

PrepareData.com/PrepareData.Web/Views/Shared/_TopBar.cshtml
<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
            <a href="#!" class="brand-logo">
                @*<img src="/content/images/alliance-logo.png" style="width:50px;height:50px;" alt="alliance logo" />*@
                <span class="logo-text"> 千睿医蟹网后台管理</span>
            </a>
            <ul class="right hide-on-med-and-down">
                @Html.Action("LanguageSelection", "Layout")
                @Html.Action("UserMenuOrLoginLink", "Layout")
                <li id="updatePwd"><a><i class="fa fa-gear"></i> 修改密码</a></li>
            </ul>
        </div>
    </nav>
    <ul id="slide-out" class="side-nav fixed">
        <li class="card-panel" style="margin: 0;padding: 23px;background-color: #ee6e73;"></li>
        @Html.Action("TopMenu", "Layout", new { activeMenu = ViewBag.ActiveMenu })
    </ul>
</div>
<div class="modal" id="modalEdit" tabindex="-1" role="dialog">
    <div class="modal-content">
        <form name="tenantCreateForm" role="form" class="form-validation">
            <h4><span>@L("Edit")</span></h4>
            <div class="row">
                <div class="input-field col s12 l12">
                    <label>@L("OldPassword")</label>
                    <input type="password" id="OldPassword" name="OldPassword">
                </div>
                <div class="input-field col s12 l12">
                    <label>@L("NewPassword1")</label>
                    <input type="password" id="NewPassword1" name="Password">
                </div>
                <div class="input-field col s12 l12">
                    <label>@L("NewPassword2")</label>
                    <input type="password" id="NewPassword2">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn modal-action waves-effect waves-green margin-right-5 updateBtn"><i class="fa fa-save"></i> @L("Submit")</button>
                    <button type="button" class="btn grey modal-close waves-effect waves-green margin-right-5"><i class="fa fa-reply"></i> @L("Cancel")</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="~/Scripts/jquery-2.2.0.min.js"></script>
<script>
    $(function () {
        var _userService = abp.services.app.user;

        var _$modal = $("#modalEdit");

        $(document).on("click", "#updatePwd", function () {
            $("#NewPassword1").val("");
            $("#NewPassword2").val("");
            $("#OldPassword").val("");
            $("#modalEdit").openModal();
        });

        $(document).on("click", ".updateBtn", function () {
            debugger;
            var newPassword1 = $("#NewPassword1").val();
            var newPassword2 = $("#NewPassword2").val();
            var oldPasssword = $("#OldPassword").val();
            if (newPassword1 == newPassword2) {
                var model = {
                    OldPassword: oldPasssword,
                    Password: newPassword2
                };
                _userService.changPwd(model).done(function () {
                    abp.notify.success("修改成功！");
                    _$modal.closeModal();
                }).always(function () {
                    abp.ui.clearBusy(_$modal);
                });
            }
            else {
                abp.message.info("两次输入密码不一致！");
                $("#NewPassword1").val("");
                $("#NewPassword2").val("");
                return false;
            }
        
        });
    })
</script>